/**
 * Beam's one piece of server code.
 *
 * Everything else about Beam is a static site — screenings.json/films.json
 * are generated by the Python pipeline and just served as files (see
 * wrangler.toml's [assets] block). Push notifications are the one feature
 * that genuinely needs an always-on server component (the planning doc
 * flagged this from the start): something has to hold each subscriber's
 * push subscription and watched films, and something has to notice — on a
 * schedule, independent of anyone having the app open — when a watched film
 * gets a real screening.
 *
 * Two moving parts:
 *   - `fetch()` handles two tiny API routes the frontend calls
 *     (subscribe/unsubscribe) and falls through to the static assets for
 *     everything else — this is still fundamentally the same static site.
 *   - `scheduled()` runs on the cron in wrangler.toml (shortly after the
 *     weekly scrape/deploy) and does the actual notifying.
 *
 * Storage is one Cloudflare KV namespace (binding: SUBSCRIPTIONS), keyed by
 * a hash of each subscription's endpoint — that's the natural stable id for
 * "one browser's push subscription" and needs no separate user-id scheme.
 */

import { buildPushHTTPRequest } from "@pushforge/builder";

const ADMIN_CONTACT = "mailto:matej.porizek@gmail.com";

function jsonResponse(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json" },
  });
}

async function subscriptionKey(subscription) {
  const bytes = new TextEncoder().encode(subscription.endpoint);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function handleSubscribe(request, env) {
  const { subscription, filmIds } = await request.json();
  if (!subscription || !subscription.endpoint || !Array.isArray(filmIds)) {
    return jsonResponse({ error: "expected { subscription, filmIds }" }, 400);
  }

  const key = await subscriptionKey(subscription);
  const existing = await env.SUBSCRIPTIONS.get(key, "json");
  // Keep whichever already-notified ids are still relevant (still in the
  // client's current watchlist) — a film dropped from the watchlist entirely
  // doesn't need to stay in this list forever, but one still being watched
  // must never be re-notified just because the client re-synced the list.
  const notifiedFilmIds = (existing?.notifiedFilmIds || []).filter((id) => filmIds.includes(id));

  await env.SUBSCRIPTIONS.put(key, JSON.stringify({ subscription, filmIds, notifiedFilmIds }));
  return jsonResponse({ ok: true });
}

async function handleUnsubscribe(request, env) {
  const { subscription } = await request.json();
  if (!subscription || !subscription.endpoint) {
    return jsonResponse({ error: "expected { subscription }" }, 400);
  }
  await env.SUBSCRIPTIONS.delete(await subscriptionKey(subscription));
  return jsonResponse({ ok: true });
}

/** A film-like record's Czech title, however the caller has it at hand. */
function titleFor(film) {
  return (film && film.title_cz) || "";
}

function notificationFor(titles) {
  if (titles.length === 1) {
    return { title: "Premiéra!", body: `${titles[0]} už hraje.` };
  }
  const shown = titles.slice(0, 3).join(", ");
  const rest = titles.length > 3 ? ` a ${titles.length - 3} další` : "";
  return { title: "Premiéry!", body: `${shown}${rest} už hrají.` };
}

/**
 * Actually deliver one push message to one subscriber, via the standard Web
 * Push protocol (VAPID-signed, RFC 8291-encrypted — buildPushHTTPRequest
 * handles both). Shared by the real weekly check and the manual test route
 * below, since "send a message to this subscription" is exactly the same
 * operation either way — only where the payload and the list of recipients
 * come from differs.
 *
 * Returns "sent", "pruned" (the push service says this subscription is gone,
 * and it's been deleted from KV — nothing left to track), or "failed" (a
 * transient error; left alone to retry later, since a wrong "already sent" is
 * worse than an extra retry).
 */
async function sendPush(key, record, payload, env) {
  try {
    const { endpoint, headers, body } = await buildPushHTTPRequest({
      privateJWK: env.VAPID_PRIVATE_KEY,
      subscription: record.subscription,
      message: {
        payload,
        adminContact: ADMIN_CONTACT,
        options: { ttl: 86400, urgency: "high" },
      },
    });
    const response = await fetch(endpoint, { method: "POST", headers, body });

    if (response.status === 404 || response.status === 410) {
      await env.SUBSCRIPTIONS.delete(key);
      return "pruned";
    }
    return response.ok ? "sent" : "failed";
  } catch (error) {
    console.error(`push failed for ${key}: ${error}`);
    return "failed";
  }
}

/**
 * The weekly check. Runs independently of whether anyone has the app open —
 * that's the entire point of a *push* notification.
 */
async function checkAndNotify(env) {
  const origin = "https://beam.matej-porizek.workers.dev";
  const [screeningsRes, filmsRes] = await Promise.all([
    env.ASSETS.fetch(`${origin}/data/screenings.json`),
    env.ASSETS.fetch(`${origin}/data/films.json`),
  ]);
  const screeningsData = await screeningsRes.json();
  const filmsData = await filmsRes.json();

  const screeningFilmIds = new Set(screeningsData.screenings.map((s) => s.film_id));
  const filmsById = new Map(filmsData.films.map((f) => [f.film_id, f]));

  const list = await env.SUBSCRIPTIONS.list();
  let notified = 0;
  let pruned = 0;

  for (const { name: key } of list.keys) {
    const record = await env.SUBSCRIPTIONS.get(key, "json");
    if (!record) continue;

    const readyIds = record.filmIds.filter(
      (id) => screeningFilmIds.has(id) && !record.notifiedFilmIds.includes(id)
    );
    if (!readyIds.length) continue;

    const titles = readyIds.map((id) => titleFor(filmsById.get(id))).filter(Boolean);
    if (!titles.length) continue; // a film_id we can't name yet — wait, don't guess

    const result = await sendPush(key, record, notificationFor(titles), env);
    if (result === "pruned") pruned++;
    if (result === "sent") {
      record.notifiedFilmIds.push(...readyIds);
      await env.SUBSCRIPTIONS.put(key, JSON.stringify(record));
      notified++;
    }
  }

  console.log(`Push check: ${notified} notified, ${pruned} stale subscriptions pruned.`);
}

/**
 * Manual test route: sends a real push, through the exact same code path as
 * a genuine premiere notification, to every currently-subscribed browser.
 * Doesn't touch notifiedFilmIds or any watched-film logic — this is purely
 * "does a message actually arrive", independent of any real screening data.
 *
 * TEMPORARY. No auth on it — acceptable for a single-user personal app where
 * the worst case is an unwanted test notification, not a real security
 * concern, but this should come back out once Matěj has confirmed delivery
 * at least once; it doesn't belong in the app long-term.
 */
async function handleTestPush(env) {
  const list = await env.SUBSCRIPTIONS.list();
  const results = [];
  for (const { name: key } of list.keys) {
    const record = await env.SUBSCRIPTIONS.get(key, "json");
    if (!record) continue;
    const result = await sendPush(
      key,
      record,
      { title: 'Beam funguje!', body: 'Testovací upozornění dorazilo v pořádku.' },
      env
    );
    results.push({ key, result });
  }
  return jsonResponse({ results });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (request.method === "POST" && url.pathname === "/api/push/subscribe") {
      return handleSubscribe(request, env);
    }
    if (request.method === "POST" && url.pathname === "/api/push/unsubscribe") {
      return handleUnsubscribe(request, env);
    }
    if (request.method === "POST" && url.pathname === "/api/push/test") {
      return handleTestPush(env);
    }

    // Everything else is the static site Beam has always been.
    return env.ASSETS.fetch(request);
  },

  async scheduled(event, env, ctx) {
    ctx.waitUntil(checkAndNotify(env));
  },
};
